//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otdel_kadrov.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public int ID { get; set; }
        public int ID_Soiskateli { get; set; }
        public int ID_Rabotodateli { get; set; }
        public string Dolznost { get; set; }
    
        public virtual Rabotodateli Rabotodateli { get; set; }
        public virtual Soiskateli Soiskateli { get; set; }
    }
}
