//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otdel_kadrov.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Otdel_kadrovEntities : DbContext
    {
        private static Otdel_kadrovEntities _context;
        public static Otdel_kadrovEntities GetContext()
        {
            if (_context == null)
                _context = new Otdel_kadrovEntities();
            return _context;
        }
        public Otdel_kadrovEntities()
            : base("name=Otdel_kadrovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dogovor> Dogovors { get; set; }
        public virtual DbSet<Rabotodateli> Rabotodatelis { get; set; }
        public virtual DbSet<Soiskateli> Soiskatelis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
